### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by lyghtkruz** [xgh69/PvpToggle#5]
I'm running craftbukkit 1.8 and your plugin seems to be looking for 'worldguard' which I don't have.  Your plugin states WorldGuard is supported, not required.  I tried the 2.1 and 2.0 versions, they do the same thing.

[18:18:39 ERROR]: Error occurred while enabling PvpToggle v2.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldguard/protection/flags/Flag
        at me.xgh69.pvptoggle.main.PvpToggle.onEnable(PvpToggle.java:130) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[craftbukkit_server.jar:git-Bukkit-18fbb24]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [craftbukkit_server.jar:git-Bukkit-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit_server.jar:git-Bukkit-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:342) [craftbukkit_server.jar:git-Bukkit-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:314) [craftbukkit_server.jar:git-Bukkit-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:406) [craftbukkit_server.jar:git-Bukkit-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:370) [craftbukkit_server.jar:git-Bukkit-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:325) [craftbukkit_server.jar:git-Bukkit-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:235) [craftbukkit_server.jar:git-Bukkit-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:504) [craftbukkit_server.jar:git-Bukkit-18fbb24]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.protection.flags.Flag
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_71]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77) ~[craftbukkit_server.jar:git-Bukkit-18fbb24]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[craftbukkit_server.jar:git-Bukkit-18fbb24]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_71]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_71]
        ... 12 more

**Comment by MarcinWieczorek** [comment]
I think I can try fixing this tomorrow unless the author wants to do that himself.

**Comment by lyghtkruz** [comment]
I'll keep an eye out.  I'm setting up a server for some elementary students and wanted to give people the option to enable or disable PVP.  This looked promising :)

**Comment by MarcinWieczorek** [comment]
I actually forgot

**Comment by lyghtkruz** [comment]
Don't worry about it. I appreciate it. I installed world edit which was the
requirement and it works fine. Turns out I liked world edit :)

I posted a comment on the plug-in page with the links to world guard and
edit, in case anyone had the same problem

-Kruz

**Comment by MarcinWieczorek** [comment]
ok ;)
